const request = require('supertest');
const { expect } = require('expect');
const _ = require('lodash');

const database = require('../../../lib/database-in-memory');
const databaseConfiguration = require('../../../lib/database-configuration');

const config = require('../../../config/config');
const login = require('../../shared/login');
const { cloneForCreate } = require('../../shared/clone-for-create');

const logger = require('../../../lib/logger');
logger.level = 'debug';

// modified and created properties will be set before calling REST API
// stix.id property will be created by REST API
const initialObjectData = {
  workspace: {
    workflow: {
      state: 'work-in-progress',
    },
  },
  stix: {
    name: 'analytic-1',
    spec_version: '2.1',
    type: 'x-mitre-analytic',
    // Note: external_references will be generated by backend
    description: 'Description of an analytic',
    object_marking_refs: ['marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168'],
    created_by_ref: 'identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5',
    x_mitre_version: '1.0',
    x_mitre_attack_spec_version: '3.3.0',
    x_mitre_platforms: ['windows'],
    x_mitre_domains: ['enterprise-attack'],
    x_mitre_mutable_elements: [
      {
        field: 'fieldOne',
        description: 'Description of fieldOne',
      },
      {
        field: 'fieldTwo',
        description: 'Description of fieldTwo',
      },
    ],
  },
};

describe('Analytics API', function () {
  let app;
  let passportCookie;

  before(async function () {
    // Establish the database connection
    // Use an in-memory database that we spin up for the test
    await database.initializeConnection();

    // Check for a valid database configuration
    await databaseConfiguration.checkSystemConfiguration();

    // Initialize the express app
    app = await require('../../../index').initializeApp();

    // Log into the app
    passportCookie = await login.loginAnonymous(app);
  });

  it('GET /api/analytics returns an empty array of analytics', async function () {
    const res = await request(app)
      .get('/api/analytics')
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(200)
      .expect('Content-Type', /json/);

    // We expect to get an empty array
    const analytics = res.body;
    expect(analytics).toBeDefined();
    expect(Array.isArray(analytics)).toBe(true);
    expect(analytics.length).toBe(0);
  });

  it('POST /api/analytics does not create an empty analytic', async function () {
    const body = {};
    await request(app)
      .post('/api/analytics')
      .send(body)
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(400);
  });

  let analytic1;
  it('POST /api/analytics creates a analytic', async function () {
    const timestamp = new Date().toISOString();
    initialObjectData.stix.created = timestamp;
    initialObjectData.stix.modified = timestamp;
    const body = initialObjectData;
    const res = await request(app)
      .post('/api/analytics')
      .send(body)
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(201)
      .expect('Content-Type', /json/);

    // We expect to get the created analytic
    analytic1 = res.body;
    expect(analytic1).toBeDefined();
    expect(analytic1.stix).toBeDefined();
    expect(analytic1.stix.id).toBeDefined();
    expect(analytic1.stix.created).toBeDefined();
    expect(analytic1.stix.modified).toBeDefined();
    expect(analytic1.stix.x_mitre_attack_spec_version).toBe(config.app.attackSpecVersion);
    expect(analytic1.stix.x_mitre_domains).toBeDefined();
    expect(Array.isArray(analytic1.stix.x_mitre_domains)).toBe(true);
    expect(analytic1.stix.x_mitre_domains.length).toBe(1);

    expect(analytic1.stix.x_mitre_mutable_elements).toBeDefined();
    expect(Array.isArray(analytic1.stix.x_mitre_mutable_elements)).toBe(true);
    expect(analytic1.stix.x_mitre_mutable_elements.length).toBe(2);
  });

  it('GET /api/analytics returns the added analytic', async function () {
    const res = await request(app)
      .get('/api/analytics')
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(200)
      .expect('Content-Type', /json/);

    // We expect to get one analytic in an array
    const analytics = res.body;
    expect(analytics).toBeDefined();
    expect(Array.isArray(analytics)).toBe(true);
    expect(analytics.length).toBe(1);
  });

  it('GET /api/analytics/:id should not return a analytic when the id cannot be found', async function () {
    await request(app)
      .get('/api/analytics/not-an-id')
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(404);
  });

  it('GET /api/analytics/:id returns the added analytic', async function () {
    const res = await request(app)
      .get('/api/analytics/' + analytic1.stix.id)
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(200)
      .expect('Content-Type', /json/);

    // We expect to get one analytic in an array
    const analytics = res.body;
    expect(analytics).toBeDefined();
    expect(Array.isArray(analytics)).toBe(true);
    expect(analytics.length).toBe(1);

    const analytic = analytics[0];
    expect(analytic).toBeDefined();
    expect(analytic.stix).toBeDefined();
    expect(analytic.stix.id).toBe(analytic1.stix.id);
    expect(analytic.stix.type).toBe(analytic1.stix.type);
    expect(analytic.stix.name).toBe(analytic1.stix.name);
    expect(analytic.stix.spec_version).toBe(analytic1.stix.spec_version);
    expect(analytic.stix.object_marking_refs).toEqual(
      expect.arrayContaining(analytic1.stix.object_marking_refs),
    );
    expect(analytic.stix.created_by_ref).toBe(analytic1.stix.created_by_ref);
    expect(analytic.stix.x_mitre_version).toBe(analytic1.stix.x_mitre_version);
    expect(analytic.stix.x_mitre_attack_spec_version).toBe(
      analytic1.stix.x_mitre_attack_spec_version,
    );

    expect(analytic.stix.x_mitre_mutable_elements).toBeDefined();
    expect(Array.isArray(analytic.stix.x_mitre_mutable_elements)).toBe(true);
    expect(analytic.stix.x_mitre_mutable_elements.length).toBe(
      analytic1.stix.x_mitre_mutable_elements.length,
    );
  });

  it('PUT /api/analytics updates a analytic', async function () {
    const originalModified = analytic1.stix.modified;
    const timestamp = new Date().toISOString();
    analytic1.stix.modified = timestamp;
    analytic1.stix.description = 'This is an updated analytic.';
    const body = analytic1;
    const res = await request(app)
      .put('/api/analytics/' + analytic1.stix.id + '/modified/' + originalModified)
      .send(body)
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(200)
      .expect('Content-Type', /json/);

    // We expect to get the updated analytic
    const analytic = res.body;
    expect(analytic).toBeDefined();
    expect(analytic.stix.id).toBe(analytic1.stix.id);
    expect(analytic.stix.modified).toBe(analytic1.stix.modified);
  });

  it('POST /api/analytics does not create a analytic with the same id and modified date', async function () {
    const body = cloneForCreate(analytic1);
    await request(app)
      .post('/api/analytics')
      .send(body)
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(409);
  });

  let analytic2;
  it('POST /api/analytics should create a new version of a analytic with a duplicate stix.id but different stix.modified date', async function () {
    const body = cloneForCreate(analytic1);
    const timestamp = new Date().toISOString();
    body.stix.modified = timestamp;
    const res = await request(app)
      .post('/api/analytics')
      .send(body)
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(201)
      .expect('Content-Type', /json/);

    // We expect to get the created analytic
    analytic2 = res.body;
    expect(analytic2).toBeDefined();
  });

  let analytic3;
  it('POST /api/analytics should create a new version of a analytic with a duplicate stix.id but different stix.modified date', async function () {
    const body = cloneForCreate(analytic1);
    const timestamp = new Date().toISOString();
    body.stix.modified = timestamp;
    const res = await request(app)
      .post('/api/analytics')
      .send(body)
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(201)
      .expect('Content-Type', /json/);

    // We expect to get the created analytic
    analytic3 = res.body;
    expect(analytic3).toBeDefined();
  });

  it('GET /api/analytics returns the latest added analytic', async function () {
    const res = await request(app)
      .get('/api/analytics/' + analytic3.stix.id)
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(200)
      .expect('Content-Type', /json/);

    // We expect to get one analytic in an array
    const analytics = res.body;
    expect(analytics).toBeDefined();
    expect(Array.isArray(analytics)).toBe(true);
    expect(analytics.length).toBe(1);
    const analytic = analytics[0];
    expect(analytic.stix.id).toBe(analytic3.stix.id);
    expect(analytic.stix.modified).toBe(analytic3.stix.modified);
  });

  it('GET /api/analytics returns all added analytics', async function () {
    const res = await request(app)
      .get('/api/analytics/' + analytic1.stix.id + '?versions=all')
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(200)
      .expect('Content-Type', /json/);

    // We expect to get two analytics in an array
    const analytics = res.body;
    expect(analytics).toBeDefined();
    expect(Array.isArray(analytics)).toBe(true);
    expect(analytics.length).toBe(3);
  });

  it('GET /api/analytics/:id/modified/:modified returns the first added analytic', async function () {
    const res = await request(app)
      .get('/api/analytics/' + analytic1.stix.id + '/modified/' + analytic1.stix.modified)
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(200)
      .expect('Content-Type', /json/);

    // We expect to get one analytic in an array
    const analytic = res.body;
    expect(analytic).toBeDefined();
    expect(analytic.stix).toBeDefined();
    expect(analytic.stix.id).toBe(analytic1.stix.id);
    expect(analytic.stix.modified).toBe(analytic1.stix.modified);
  });

  it('GET /api/analytics/:id/modified/:modified returns the second added analytic', async function () {
    const res = await request(app)
      .get('/api/analytics/' + analytic2.stix.id + '/modified/' + analytic2.stix.modified)
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(200)
      .expect('Content-Type', /json/);

    // We expect to get one analytic in an array
    const analytic = res.body;
    expect(analytic).toBeDefined();
    expect(analytic.stix).toBeDefined();
    expect(analytic.stix.id).toBe(analytic2.stix.id);
    expect(analytic.stix.modified).toBe(analytic2.stix.modified);
  });

  it('DELETE /api/analytics/:id should not delete a analytic when the id cannot be found', async function () {
    await request(app)
      .delete('/api/analytics/not-an-id')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(404);
  });

  it('DELETE /api/analytics/:id/modified/:modified deletes a analytic', async function () {
    await request(app)
      .delete('/api/analytics/' + analytic1.stix.id + '/modified/' + analytic1.stix.modified)
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(204);
  });

  it('DELETE /api/analytics/:id should delete all the analytics with the same stix id', async function () {
    await request(app)
      .delete('/api/analytics/' + analytic2.stix.id)
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(204);
  });

  describe('Search functionality with detection strategies', function () {
    // Test data for detection strategy search functionality
    const detectionStrategyData = {
      workspace: {
        workflow: {
          state: 'work-in-progress',
        },
      },
      stix: {
        name: 'Network Connection Creation Detection Strategy',
        spec_version: '2.1',
        type: 'x-mitre-detection-strategy',
        description: 'Strategy for detecting network connections',
        object_marking_refs: ['marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168'],
        created_by_ref: 'identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5',
        x_mitre_version: '1.0',
        x_mitre_attack_spec_version: '3.3.0',
        x_mitre_domains: ['enterprise-attack'],
        x_mitre_analytic_refs: [],
      },
    };

    let searchTestAnalytic;
    let searchTestDetectionStrategy;

    it('POST /api/analytics creates a search test analytic', async function () {
      const timestamp = new Date().toISOString();
      const searchAnalyticData = _.cloneDeep(initialObjectData);
      searchAnalyticData.stix.name = 'Search Test Analytic';
      searchAnalyticData.stix.created = timestamp;
      searchAnalyticData.stix.modified = timestamp;

      const res = await request(app)
        .post('/api/analytics')
        .send(searchAnalyticData)
        .set('Accept', 'application/json')
        .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
        .expect(201)
        .expect('Content-Type', /json/);

      searchTestAnalytic = res.body;
      expect(searchTestAnalytic).toBeDefined();
      expect(searchTestAnalytic.stix.id).toBeDefined();
    });

    it('POST /api/detection-strategies creates a detection strategy that references the analytic', async function () {
      const timestamp = new Date().toISOString();
      detectionStrategyData.stix.created = timestamp;
      detectionStrategyData.stix.modified = timestamp;
      detectionStrategyData.stix.x_mitre_analytic_refs = [searchTestAnalytic.stix.id];

      const res = await request(app)
        .post('/api/detection-strategies')
        .send(detectionStrategyData)
        .set('Accept', 'application/json')
        .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
        .expect(201)
        .expect('Content-Type', /json/);

      searchTestDetectionStrategy = res.body;
      expect(searchTestDetectionStrategy).toBeDefined();
      expect(searchTestDetectionStrategy.stix.id).toBeDefined();
      expect(searchTestDetectionStrategy.stix.x_mitre_analytic_refs).toContain(
        searchTestAnalytic.stix.id,
      );
    });

    it('GET /api/analytics?search should find analytic by its own name', async function () {
      // Analytics are named after their attack_id (e.g., AN0001)
      const searchTerm = searchTestAnalytic.stix.name;
      const res = await request(app)
        .get(`/api/analytics?search=${encodeURIComponent(searchTerm)}`)
        .set('Accept', 'application/json')
        .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
        .expect(200)
        .expect('Content-Type', /json/);

      const analytics = res.body;
      expect(analytics).toBeDefined();
      expect(Array.isArray(analytics)).toBe(true);
      expect(analytics.length).toBe(1);
      expect(analytics[0].stix.id).toBe(searchTestAnalytic.stix.id);
    });

    it('GET /api/analytics?search should find analytic by detection strategy name', async function () {
      const res = await request(app)
        .get('/api/analytics?search=Network Connection Creation')
        .set('Accept', 'application/json')
        .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
        .expect(200)
        .expect('Content-Type', /json/);

      const analytics = res.body;
      expect(analytics).toBeDefined();
      expect(Array.isArray(analytics)).toBe(true);
      expect(analytics.length).toBe(1);
      expect(analytics[0].stix.id).toBe(searchTestAnalytic.stix.id);
    });

    it('GET /api/analytics?search should find analytic by partial detection strategy name', async function () {
      const res = await request(app)
        .get('/api/analytics?search=Network Connection')
        .set('Accept', 'application/json')
        .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
        .expect(200)
        .expect('Content-Type', /json/);

      const analytics = res.body;
      expect(analytics).toBeDefined();
      expect(Array.isArray(analytics)).toBe(true);
      expect(analytics.length).toBe(1);
      expect(analytics[0].stix.id).toBe(searchTestAnalytic.stix.id);
    });

    it('GET /api/analytics?search should not find analytic with non-existent search term', async function () {
      const res = await request(app)
        .get('/api/analytics?search=NonExistentTerm')
        .set('Accept', 'application/json')
        .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
        .expect(200)
        .expect('Content-Type', /json/);

      const analytics = res.body;
      expect(analytics).toBeDefined();
      expect(Array.isArray(analytics)).toBe(true);
      expect(analytics.length).toBe(0);
    });

    after(async function () {
      // Clean up test data
      if (searchTestDetectionStrategy) {
        await request(app)
          .delete('/api/detection-strategies/' + searchTestDetectionStrategy.stix.id)
          .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
          .expect(204);
      }

      if (searchTestAnalytic) {
        await request(app)
          .delete('/api/analytics/' + searchTestAnalytic.stix.id)
          .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
          .expect(204);
      }
    });
  });

  it('GET /api/analytics returns an empty array of analytics', async function () {
    const res = await request(app)
      .get('/api/analytics')
      .set('Accept', 'application/json')
      .set('Cookie', `${passportCookie.name}=${passportCookie.value}`)
      .expect(200)
      .expect('Content-Type', /json/);

    // We expect to get an empty array
    const analytics = res.body;
    expect(analytics).toBeDefined();
    expect(Array.isArray(analytics)).toBe(true);
    expect(analytics.length).toBe(0);
  });

  after(async function () {
    await database.closeConnection();
  });
});
